config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :users
  # get 'items/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :categories
  
  resources :items do
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      get 'search'
      get 'post_done'
      get 'delete_done'
      get 'detail_search'
      get 'update_done'
    end
  end
  
  resources :destinations

  resources :cards, except: :index do
    collection do
      get 'registration_done'
      get 'delete_done'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  

  


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  accepts_nested_attributes_for :brand, allow_destroy: true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  #Itemモデルで 「購入者」「出品者」を取り出せるようにする。
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :card

 
  validates :name,                         presence: true,    length: { maximum: 40 } 
  validates :introduction,             presence: true,    length: { maximum: 1000 } 
  validates :category_id,                     presence: true
  validates :item_condition,                  presence: true
  validates :quantity,               presence: true
  validates :cost,                 presence: true
  validates :prefecture,              presence: true
  validates :days,          presence: true
  validates :price,             presence: true, numericality: {greater_than_or_equal_to: 300}
  validates :images, presence: true
  

  extend ActiveHash::Associations::ActiveRecordExtensions
  # belongs_to_active_hash :category
  # belongs_to_active_hash :size
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :prefecture_fire
  belongs_to_active_hash :delivery_days
  belongs_to_active_hash :condition
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :category_parent_array, only: [:new, :create, :edit, :update]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :show_all_instance, only: [:show, :edit, :update, :destroy]
  before_action :check_item_details, only: [:post_done, :update_done]
  before_action :condition, only: [:show]
  before_action :set_prefecture, only: [:show]
  before_action :delivery_fee, only: [:show]
  before_action :delivery_days, only: [:show]
  before_action :category_map, only: [:edit, :update]
  # before_action :set_ransack,only: [:search, :detail_search]
  before_action :authenticate_user! , except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    # @items = Item.all.order('id DESC').limit(3)
    @items = Item.includes(:images).order('id DESC').limit(3)
  end

  def new
    @item = Item.new
    @item.images.new
    @item.build_brand

  end

  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to  post_done_items_path
    else
      @item.images.new
      @item.build_brand
      render :new
    end
  end

  def post_done
    @item = Item.where(seller_id: current_user.id).last
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy

    if  @item.destroy
      redirect_to  delete_done_items_path
    else
      flash.now[:alert] = '削除できませんでした'
      render :show
    end
  end

  def show
    if @item.quantity == 0

      redirect_to buy_card_path

    # @seller = @items.seller.name
    end
  end

  def search
    @search_items = Item.search(params[:keyword])
    @keyword = params[:keyword]
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  private
  def condition
    @condition = Condition.find(@item.item_condition)
  end
   
  def set_prefecture
    @prefecture = PrefectureFire.find(@item.prefecture)
  end

  def delivery_fee
    @deliveryfee = DeliveryFee.find(@item.cost)
  end

  def delivery_days
    @deliverydays = DeliveryDays.find(@item.days)
  end

  def item_params
    params.require(:item).permit(:name, :introduction, :category_id, :item_condition, :price, :prefecture, :cost, :days,:brand_id, :quantity, images_attributes: [:id, :image, :_destroy], brand_attributes: [:id, :name ]).merge(seller_id: current_user.id)
  end

  def category_parent_array
    @category_parent_array = Category.where(ancestry: nil).each do |parent|
    end
  end

  def set_item
    
    @item = Item.find(params[:id])
  end

  def check_item_details
    @item = Item.where(seller_id: current_user.id).last
  end

  def show_all_instance
    @user = User.find(@item.seller_id)
    @images = Image.where(item_id: params[:id])
    @images_first = Image.where(item_id: params[:id]).first
    @category_id = @item.category_id
    @category_parent = Category.find(@category_id).parent.parent
    @category_child = Category.find(@category_id).parent
    @category_grandchild = Category.find(@category_id)
  end

  def category_map
    grandchild = @item.category
    child = grandchild.parent
    if @category_id == 46 or @category_id == 74 or @category_id == 134 or @category_id == 142 or @category_id == 147 or @category_id == 150 or @category_id == 158
    else
      @parent_array = []
      @parent_array << @item.category.parent.parent.name
      @parent_array << @item.category.parent.parent.id
    end
    @category_children_array = Category.where(ancestry: child.ancestry)
    @child_array = []
    @child_array << child.name
    @child_array << child.id

    @category_grandchildren_array = Category.where(ancestry: grandchild.ancestry)
    @grandchild_array = []
    @grandchild_array << grandchild.name
    @grandchild_array << grandchild.id
  end


  def correct_user
    @item = Item.find(params[:id])
    if @item.seller_id != current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_banner.html.haml
.Banner
  .inner
    %h2.inner__title 誰でも簡単、人生を変えるフリマアプリ
    %p.inner__test 今すぐ無料ダウンロード
    .inner__icon
      %a.btnA{herf: "#"}
      = image_tag asset_path("apple.png")
      %a.btnG{herf: "#"}
      = image_tag asset_path("google.png")

app/views/items/_footer-2.html.haml
.Footer
  .Footer__contents
    .Footer__contents--content

      
      %ul
        %li.head
          FURIMAについて
        %li
        = link_to "会社概要（運営会社）", :root, class: 'Button'
        %li
        = link_to "プライバシーポリシー", :root, class: 'Button'
        %li
        = link_to "FURIMA利用規約", :root, class: 'Button'
        %li
        = link_to "ポイントに関する特約", :root, class: 'Button'    
      %ul
        %li.head
          FURIMAを見る
        %li
        = link_to "カテゴリー一覧", :root, class: 'Button'
        %li
        = link_to "ブランド一覧", :root, class: 'Button'     
      %ul
        %li.head
          ヘルプ＆ガイド
        %li
        = link_to "FURIMAガイド", :root, class: 'Button'
        %li
        = link_to "FURIMAロゴ利用ガイドライン", :root, class: 'Button'
        %li
        = link_to "お知らせ", :root, class: 'Button'
  .Footer__logo
  = image_tag asset_path ('logo-white.png'), alt: "次へ",width:"150px",height:"50px"
  %p©FURIMA

app/views/items/_footer.html.haml
.Footer
  .Footer__contents
    .Footer__contents--content

      
      %ul
        %li.head
          FURIMAについて
        %li
        = link_to "会社概要（運営会社）", :root, class: 'Button'
        %li
        = link_to "プライバシーポリシー", :root, class: 'Button'
        %li
        = link_to "FURIMA利用規約", :root, class: 'Button'
        %li
        = link_to "ポイントに関する特約", :root, class: 'Button'    
      %ul
        %li.head
          FURIMAを見る
        %li
        = link_to "カテゴリー一覧", :root, class: 'Button'
        %li
        = link_to "ブランド一覧", :root, class: 'Button'     
      %ul
        %li.head
          ヘルプ＆ガイド
        %li
        = link_to "FURIMAガイド", :root, class: 'Button'
        %li
        = link_to "FURIMAロゴ利用ガイドライン", :root, class: 'Button'
        %li
        = link_to "お知らせ", :root, class: 'Button'
  .Footer__logo
  = image_tag asset_path ('logo-white.png'), alt: "次へ",width:"150px",height:"50px"
  %p©FURIMA

= link_to new_item_path do
  .purchaseBtn
    .purchaseBtn__text 出品する
    .purchaseBtn__icon
      %i.fas.fa-camera

app/views/items/_form.html.haml
- if user_signed_in?
  - content_for :css do
    = stylesheet_link_tag 'modules/new_items'
  -# .new__page__header
  -# = link_to image_tag(asset_path("logo.png"), root_path

  

  .header
  = link_to root_path do
    = image_tag asset_path ('logo.png'), alt: 'logo', width: "150px", height: "60px"
  - if @item.errors.any?
    .alert
      %ul
        -@item.errors.full_messages.each do |message|
          %li= message
  
  .new_item 
  = form_for @item do |f|
    .new_item__name
      出品画像
      .new_item__name--required
        [必須]
    .pic-up
      %input{type: "file", class: "sell__main__content__file__up"}
        %i.fas.fa-camera
      %pre.sell__main__content__file__box__inner
        写真を投稿（10枚まで選択できます）
    .sell__main__content__file__box
      .js
        #image-box
          #previews
            - if @item.persisted?
              - @item.images.each_with_index do |image, i|
                = image_tag image.src.url, data: { index: i }, width: "100", height: '100'
            = f.fields_for :images do |image|
              .js-file_group{"data-index" => "#{image.index}"}
                = image.file_field :image, class: 'js-file'
                %br/
                %span.js-remove 削除
            - if @item.persisted?
              = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
          - if @item.persisted?
            .js-file_group{"data-index" => "#{@item.images.count}"}
              = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][image]", class: 'js-file'
              .js-remove 削除

    -# #image-box
    -#   #previews
    -#   - if @item.persisted? 
    -#     - @item.images.each_with_index do |image, i| 
    -#       = image_tag image.src.url, data: { index: i }, width: "100", height: '100' 
    -#   = f.fields_for :images do |image|
    -#     .js-file_group{"data-index" => "#{image.index}"}
        
    -#       = image.file_field :image, class: 'js-file'
    -#       - if @item.persisted?
    -#         = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
    -#       %i.fas.fa-camera
    -#       %br/
    -#       %span.js-remove 削除


      
    .new_item__item_name
      .new_item__item_name--label
        商品名
      .new_item__item_name--required
        [必須]
    .new_item__area
      = f.text_field :name, placeholder: "４０字まで", class: "input"
      
    .new_item__introduction
      .new_item__introduction--label
        商品の説明
      .new_item__introduction--required
        [必須]
    .new_item__intro-area
      = f.text_field :introduction, placeholdr: "商品の説明（必須1000文字以内）（色、素材、重さ、定価、注意点など）", class: "input"
      
    .append__category
      .category
        .category__lavel
          .category__lavel--name 
            カテゴリー
          .category__lavel--required
            [必須]
        = f.collection_select :category_id, @category_parent_array, :id, :name, { include_blank: "選択してください"},  class: "serect_field"

    
    .new_item__brand--area
    
      .form-group.brand--container

        = f.fields_for :brand, @item.build_brand do |brand|
          = brand.label "ブランド"
         
          %div
            = brand.text_field :name, placeholder: "例）シャネル", value: "", class: "input"


    .new_item__item_condition
      .new_item__item_condition--label
        商品の状態
      .new_item__item_condition--required
        [必須]
    .new_item__item_condition-area
      -# =f.collection_select(:item_condition, Condition.all, :id, :value, { include_blank: '---' }, {class:"serect_field"} )
      = f.collection_select :item_condition, Condition.all, :id, :value

    .new_item__cost
      .new_item__cost--label
        配送料の負担
      .new_item__cost--required
        [必須]
    .new_item__cost-area
      =f.collection_select(:cost, DeliveryFee.all, :id, :value, { include_blank: '---' }, {class:"serect_field"} )

    .new_item__prefecture
      .new_item__prefecture--label
        発送元の地域
      .new_item__prefecture--required
        [必須]
    .new_item__prefecture-area
      =f.collection_select(:prefecture, PrefectureFire.all, :id, :name,{include_blank: "---"}, {class: "serect_field"} )

    .new_item__days
      .new_item__days--label
        発送元までの日数
      .new_item__days--required
        [必須] 

    .new_item__days-area
      =f.collection_select(:days, DeliveryDays.all, :id, :value, { include_blank: '---' }, {class:"serect_field"} )

    .new_item__quantity
      .new_item__quantity--label
        販売数
      .new_item__quantity--required
        [必須]
    .new_item__quantity-area
      =f.number_field :quantity, placeholder: "0", class: "input2"
      個
        
    .new_item__price
      .new_item__price--label
        販売価格
      .new_item__price--required
        [必須]
    .new_item__selling-price
      出品価格（300円〜9,999,999円）
    .new_item__selling-price-area
      =f.number_field :price, min:300, max:999999999, placeholder: "0", class: "input2"
      円
      %br
      .sales_commission
        .lavel__name
          販売手数料（10%）
        #sales_commission_price
      .sales_profit
        .lavel__name
          販売利益
        #sales_profit_proce


   
    
    
    .send
      = f.submit "出品する", class: "send__sipping_btn"

- else
  - content_for :css do
    = stylesheet_link_tag 'modules/new_items'
  .done#fullsize
    .done__title
      商品を出品するには新規会員登録またはログインが必要です
    .done__backlink
      = link_to '新規会員登録', new_user_registration_path, class: 'linkBtn'
    .done__backlink
      = link_to 'ログイン', new_user_session_path, class: 'linkBtn'

app/views/items/_header.html.haml
// Place all the styles related to the items controller here.
// They will automatically be included in application.css.
// You can use Sass (SCSS) here: http://sass-lang.com/

- content_for :css do
  = stylesheet_link_tag 'modules/items'

.Header
  .Header__Inner
    .Header__Inner--Main
      .Icon
      = link_to root_path do
        = image_tag asset_path("logo.png"), alt: "次へ",width:"140px",height:"50px", class: "icon"

      
      .searchBox
        %form{actio: "http://xxxxxxxxxxxxx.com/", metho: "get", class: "form"}
          %input{nam: "s", placeholder: "キーワードから探す", type: "text", class: "search-box"}>
          %button{type: "submit",class: "search-btn"}
            %i.fas.fa-search


    .Header__Inner--HeaderNavi
      .listsLeft
        .listsLeft__item
          -# = link_to 'categories#index' do ＃レンダー先でリンクを押すとでエラーが出るので
          = link_to '#' do
            カテゴリー
        .listsLeft__brand
          = link_to "ブランド", :root, class: 'Button'


      .listsRight
        - if user_signed_in?
          .user_nav.grid-6
            = link_to 'マイページ', user_path(current_user.id), class: 'Button'
        - else
          .grid-6
            .listsRight__login
              = link_to "ログイン", new_user_session_path, class: 'Button'
            .listsRight___new
              = link_to "新規会員登録", new_user_registration_path, class: 'Button'
            

app/views/items/_item.html.haml
= link_to '編集', edit_item_path(item)
= link_to '削除', item_path(item), method: :delete

app/views/items/delete_done.html.haml
- content_for :css do
  = stylesheet_link_tag 'modules/delete_done'

= render 'header'
.body

.done#fullsize
  .done__title
    商品を削除しました
  .done__backlink
    = link_to 'トップページへ戻る', root_path, class: 'link'


= render 'banner'

= render 'footer'

app/views/items/edit.html.haml
= render partial: 'form_edit'

app/views/items/index.html.haml
- content_for :css do
  = stylesheet_link_tag 'modules/items'

.body

  = render 'header'

  .main
    %section.topVisual
      .content
        %h2.content__title
          人生を変えるフリマアプリ
        .content__text
          FURIMAはだれでもかんたんに出品・購入できる
          %br
          フリマアプリです
        .content__btn
          %a.btnA{herf: "#"}
          = image_tag asset_path("apple.png")
          %a.btnG{herf: "#"}
          = image_tag asset_path("google.png")
    %section.secondVisual
      .second-content
        %h2.reason
          FURIMAが選ばれる3つの理由
        .reason-lists
          %ul.lists
            %li.list
              .list__image
                %span.num
                  1
                = image_tag asset_path('pict-reason-01.jpg')
              %h3.list__word
                %span.reason-word
                  3分
                ですぐに出品
              .list__text
                スマホで入力するだけで簡単に出品できる!
            %li.list
              .list__image
                %span.num
                  2
                = image_tag asset_path('pict-reason-02.jpg')
              %h3.list__word
                %span.reason-word
                  シンプル
                で使いやすい
              .list__text
                めんどくさい入力は必要なく、検索も購入もスムーズ!
            %li.list__end
              .list__image
                %span.num
                  3
                = image_tag asset_path('pict-reason-03.jpg')
              %h3.list__word
                手数料
                %span.reason-word
                  業界最安
              .list__text
                最大3%でお得に出品&購入!
    %section.middleVisual
      .middle-content
        %h2.subtitle
          会員数日本一位
        .middle-content__box
          %p.middle-content__text
            FURIMAはフリマアプリで最も人気。
            %br
            出品・購入回数も業界最多です!
            %br
            ほしかったあの商品に出会えるかもしれません。
        .btn
          %a.btnA{herf: "#"}
            = image_tag asset_path("apple.png")
          %a.btnG{herf: "#"}
            = image_tag asset_path("google.png")

    %section.featuresVisual
      %h2.feauture-title
        FURIMAの特徴
      .feauture-contents
        %section.content
          %figure.content__img
          = image_tag asset_path('icon-01.png')
          %h3.content__top
            簡単に売り買いできる
          %p.content__detail
            スマホひとつで、いつでもどこでも簡単に出品が可能!
        %section.content
          %figure.content__img
          = image_tag asset_path('icon-03.png')
          %h3.content__top
            売上金は即日振り込みに対応
          %p.content__detail
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        %section.content
          %figure.content__img
          = image_tag asset_path('icon-04.png')
          %h3.content__top
            様々な支払いに対応
          %p.content__detail
            お支払いは、クレジットカードだけでなく、ポイントは売上金など多彩な方法があります!
    %section.pickupVisual
      %h2.topic-category
        ピックアップカテゴリー
      .category-box
        .category-head
          %a.newItem{herf: "#"}
            %h3.title
              新規投稿商品
        .category-lists
        
          - @items.each do |item|
            - if item.quantity == 0
              .category-list 
                = link_to item_path(item), class: "link" do
                  .product-image
                    = image_tag item.images[0].image.url, class: "image"
                  .product-info
                    .sold-out
                      .sold
                        SOLD
                    .item-name
                      = item.name
                    .item-price
                      = "#{item.price.to_s(:delimited)}円（税込）"

          
            - else 
              .category-list
                = link_to item_path(item), class: "link" do
                  .product-image
                    = image_tag item.images[0].image.url, class: "image"
                  .product-info
                    .item-name
                      = item.name
                    .item-price
                      = "#{item.price.to_s(:delimited)}円（税込）"
                

    %section.pickupVisual
      %h2.topic-category
        ピックアップブランド
      .category-box
        .category-head
          %a.newItem{herf: "#"}
            %h3.title
              アーカイバ
        .category-lists
          .category-list
            %figure.category-list__image
            .category-list__body
              
        .category-lists
          .category-list
            .category-list__image
            = image_tag asset_path('beef.png'), width: "180px", height: "180px"
            .category-list__body
              %hs3.name テスト
              .datails
                %ul
                  %li 10000円 
                  %li
                    %i.fa.fa-star.likeIcon 1
                %p (税込)
          .category-list
            .category-list__image
            = image_tag asset_path('tantan.png'), width: "180px", height: "180px"
            .category-list__body
              %h3.name ee
              .datails
                %ul
                  %li 1000円
                  %li
                    %i.fa.fa-star.likeIcon 0
                %p (税込)
          .category-list
            .category-list__image
            = image_tag asset_path('fish.png')
            .category-list__body
              %h3.name product3
              .datails
                %ul
                  %li 30000円
                  %li
                    %i.fa.fa-star.likeIcon 0
                %p (税込)   
          

  = render 'banner'

  = render 'footer'

app/views/items/new.html.haml
= render partial: 'form'

app/views/items/post_done.html.haml
- content_for :css do
  = stylesheet_link_tag 'modules/post_done'



= render partial: "items/header"


.done
  .done__title
    商品を出品しました
  .done__backlink
    =link_to root_path, class:"link" do
      トップページへ戻る
  .done__backlink
    = link_to item_path(@item.id), class: "link" do
      出品した商品を確認する
  .done__backlink
    = link_to users_path, class: "link" do
      出品中の商品一覧を見る


= render partial: "banner"

= render partial: "items/footer"

app/views/items/show.html.haml
- content_for :css do
  = stylesheet_link_tag 'modules/show'

= render partial: "items/header"

%nav.breadCrumbs
  %ul
    %li
      %a FURIMA
    %li
      %i >
    %li
      %a ベビー・キッズ
    %li
      %i >
    %li
      %a ベビー服(男の子用)  ~95cm
    %li
      %i >
    %li
      %a アウター
    %li
      %i >
    %li
      %p 
    
.main
  .content
    .content__right
      .top__content
        .item-box
          %h2.item-box__name 
            = @item.name
          .item-box__body
            .item-box__main
              .mainPct
                = image_tag(@item.images.first.image.url, class: "main__photo")
                .subPct-box
                  - @images.each do |image|
                    .subPctList
                      = image_tag(image.image.url, class: "subPct", size: "100x100")

          .item-box__price
            %span.price
              ¥
              = @item.price.to_s(:delimited)

            .item-box__price--detail
              %span.tax
                (税込)
              %span.postage
                送料込み
            .item__detail
              = @item.introduction
          .table
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    = @user.nickname
                %tr
                  %th
                    カテゴリー
                  - if [46, 74, 134, 142, 147, 150, 158].include?(@category_id)
                    %td
                      = link_to "#{@category_child.name}","#"
                      %br= link_to "#{@category_grandchild.name}","#" 
                  -else
                    %td
                      = link_to "#{@category_parent.name}","#"
                      %br= link_to "#{@category_child.name}","#"
                      = link_to "#{@category_grandchild.name}","#"

                %tr
                  %th
                    ブランド
                  %td
                    = @item.brand.name
                %tr
                  %th
                    商品の量
                  %td
                    = @item.quantity
                %tr
                  %th
                    商品の状態
                  %td
                    = @condition.value
                %tr
                  %th
                    配送料の負担
                  %td
                    = @deliveryfee.value
                %tr
                  %th
                    発送元の地域
                  %td
                    = @prefecture.name
                %tr
                  %th
                    発送日の目安
                  %td
                    = @deliverydays.value

          .link
            .link__page
              - if current_user == @user
                = link_to "商品の編集", edit_item_path(@item.id) , class: "edit"
                = link_to "商品の削除", item_path(@item.id), method: :delete, class: "destroy"
              - else user_signed_in?
                = link_to "購入画面に進む", buy_card_path(@item.id), class: "pay"

          .optionalArea 
            %ul
              %li.optionalBtn__likeBtn
                %i.fa.fa-star
                  お気に入り 1
            %ul.optional
              %li.optionalBtn
                %a
                  %i.fa.fa-flag
                    不適切な商品の通報

        .commentBox
          %ul.commentContents
          //コメントテーブルないため以下のformは仮で作成
          %form.new_comment
            %textarea.message_form{name: "message", placeholder: "MESSAGE"}
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
            %button{type: "submit",class: "commentBtn"}
              %i.fas.fa-comment
              コメントする
      %ul.links
        %li.links__before
          = link_to "#", class: "angle__left" do
            = icon('fa', 'angle-left')
            %span 前の商品
        %li.links__after
          = link_to "#", class: "angle__right" do
            %span 後ろの商品
            = icon('fa', 'angle-right')

      .relatedItems
        .relatedItems__title
          %a
            = link_to "レディースをもっと見る"
                      
        .productLists
          .productList
            %a
              -# = link_to "#"
            .productList__img
              = image_tag asset_path('carry.png')
            .productList__body
              %h3.name
                product1
                .details  
                  %ul
                    %li
                      100000円
                    %li
                      %i.fa.fa-star.likeIcon
                        1
                  %p
                    (税込) 
= render partial: "items/banner"
= render partial: "items/footer"

app/views/items/update_done.html.haml
.done#fullsize
  .done__title
    商品情報を更新しました
  .done__backlink
    = link_to 'トップページへ戻る', root_path, class: 'link'
  .done__backlink
    = link_to '更新した商品を確認する', item_path(@item_update), class: 'link'
  .done__backlink
    = link_to '出品中の商品一覧を見る', users_path, class: 'link'