config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :users
  # get 'items/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :categories
  
  resources :items do
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      get 'search'
      get 'post_done'
      get 'delete_done'
      get 'detail_search'
      get 'update_done'
    end
  end
  
  resources :destinations

  resources :cards, except: :index do
    collection do
      get 'registration_done'
      get 'delete_done'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  

  


end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_one :destination  
  has_one :item

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :year
  belongs_to_active_hash :month
  belongs_to_active_hash :prefecture_fire
  belongs_to_active_hash :delivery_fee
end

app/controllers/card_controller.rb
 # 〜〜〜〜〜〜〜〜〜〜〜馬場元々のコードここから〜〜〜〜〜〜〜〜〜〜〜
# class CardController < ApplicationController

#   require "payjp"

  # def new
  #   card = Card.where(user_id: current_user.id)
  #   redirect_to card_index_path if card.exists?
  # end

 
  # def pay #payjpとCardのデータベース作成を実施します。
  #   Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
  #   if params['payjp-token'].blank?
  #     redirect_to new_card_path
  #   else
  #     customer = Payjp::Customer.create(
  #     # description: '登録テスト', #なくてもOK
  #     # email: current_user.email, #なくてもOK
  #     card: params['payjp-token'],
  #     # metadata: {user_id: current_user.id}
  #     ) #念の為metadataにuser_idを入れましたがなくてもOK
  #     @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      
  #     if @card.save
  #       redirect_to card_index_path
  #     else
  #       redirect_to pay_card_index_path
  #     end
  #   end
  # end

  # def delete #PayjpとCardデータベースを削除します
  #   card = Card.where(user_id: current_user.id).first
  #   if card.blank?
  #   else
  #     Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
  #     customer = Payjp::Customer.retrieve(card.customer_id)
  #     customer.delete
  #     card.delete
  #   end
  #     redirect_to new_card_path
  # end
    # def show #Cardのデータpayjpに送り情報を取り出します
  #   card = Card.where(user_id: current_user.id).first
  #   if card.blank?
  #     redirect_to new_card_path
  #   else
  #     Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
  #     customer = Payjp::Customer.retrieve(card.customer_id)
  #     @default_card_information = customer.cards.retrieve(card.card_id)
  #   end
  # end
# end
  # 〜〜〜〜〜〜〜〜〜〜〜馬場元々のコードここまで〜〜〜〜〜〜〜〜〜〜〜〜
  
  class CardsController < ApplicationController
    require 'payjp'
  
    before_action :set_item, only:[:show,:pay]
    before_action :card_present,only:[:index,:destroy]
    before_action :take_card, only:[:show,:pay]
    before_action :set_api_key
    
    def create
      if params['payjp-token'].blank?
        redirect_to action: "new"
        # トークンが取得出来てなければループ
      else
        user_id = current_user.id
        customer = Payjp::Customer.create(
        card: params['payjp-token']
        # params['payjp-token']（response.id）からcustomerを作成
        ) 
        @card = Card.new(user_id: user_id, customer_id: customer.id, card_id: customer.default_card)
        if @card.save
          flash[:notice] = '登録しました'
          redirect_to "/"
        else
          flash[:alert] = '登録できませんでした'
          redirect_to action: "new"
        end
      end
    end

    def destroy #PayjpとCardのデータベースを削除
      set_customer
      @customer.delete
      if @card.destroy #削除に成功した時にポップアップを表示します。
        flash[:notice2] = '削除しました'
        redirect_to action: "index"
      else #削除に失敗した時にアラートを表示します。
        flash[:alert2] = '削除できませんでした'
        redirect_to action: "index"
      end
    end

    def show 
      if @card.blank?
        #登録された情報がない場合にカード登録画面に移動
        flash[:alert] = '購入前にカード登録してください'
        redirect_to cards_path and return
      else
        #保管した顧客IDでpayjpから情報取得
        set_customer
        #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
        set_card_information
      end
      if current_user.prefecture == nil
          flash[:alert] = '購入前に住所登録してください'
          redirect_to new_prefecture_path
      end
    end

    def pay
      @item.update(buyer_id: current_user.id)
      # 現在のユーザーを購入者に登録
      Payjp::Charge.create(
      :amount => @item.price, 
      :customer => @card.customer_id, 
      :currency => 'jpy', #日本円
     )
      redirect_to item_purchase_index_path(@item.id)
    # 購入確認画面に遷移
    end

  
  private
  
    def set_item
      @item = Item.find(params[:id])
      @prefecture = Prefecture.find_by(user_id:current_user.id)
    end

    def card_present
      @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
    end
  
    def set_api_key
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
      binding.pry
    end
  
    def set_customer
      @customer = Payjp::Customer.retrieve(@card.customer_id)
    end
  
    def set_card_information
      @card_information = @customer.cards.retrieve(@card.card_id)
    end
  
    def take_card
      @card = Card.find_by(user_id: current_user.id)
    end
  
  end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :move_to_root
  before_action :prefecture,   only: [:buy, :pay]
  before_action :set_card,    only: [:new, :show, :destroy, :buy, :pay]
  before_action :set_item,    only: [:buy, :pay]
  before_action :authenticate_user!
  before_action :correct_user, only: [:buy, :pay]
  before_action :deliveryfee, only: [:buy, :pay]
  require "payjp"

  def new
    redirect_to card_path(current_user.id) if @card.present?
  end

  def create
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
    if params['payjp-token'].blank?
      # payjp-tokenが空ならnewへ
      redirect_to new_card_path
    else
      # payjp-tokenが入っているなら以下を実施
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to registration_done_cards_path
      else
        redirect_to new_card_path
      end
    end
  end

  def registration_done
  end

  def show
    if @card.blank?
    #登録された情報がない場合にカード登録画面に移動
      redirect_to new_card_path 
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(@card.card_id)
      case @card_info.brand
        when "Visa"
          @card_src = "visa.gif"
        when "JCB"
          @card_src = "jcb.gif"
        when "MasterCard"
          @card_src = "mc.png"
        when "American Express"
          @card_src = "amex.gif"
        when "Diners Club"
          @card_src = "diners.gif"
        when "Discover"
          @card_src = "discover.gif"
      end
    end
  end

  def destroy
    if @card.blank?
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to delete_done_cards_path
  end

  def delete_done
  end

  def buy
    if user_signed_in?
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      if @card.blank?
        @card_info = ""
      else
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @card_info = customer.cards.retrieve(@card.card_id)
        case @card_info.brand
          when "Visa"
            @card_src = "visa.gif"
          when "JCB"
            @card_src = "jcb.gif"
          when "MasterCard"
            @card_src = "mc.png"
          when "American Express"
            @card_src = "amex.gif"
          when "Diners Club"
            @card_src = "diners.gif"
          when "Discover"
            @card_src = "discover.gif"
        end
      end
    else
      redirect_to root_path
    end
  end

  def pay
    if @item.quantity == 0
      redirect_to buy_card_path(@item)
    else
      if current_user.card.present?
        Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
        charge = Payjp::Charge.create(
          amount: @item.price,
          customer: Payjp::Customer.retrieve(@card.customer_id),
          currency: 'jpy'
          )
        @item.update!(buyer_id: 2)
        # 仮テスト 0817追記↓↓↓↓↓↓↓↓↓
        @item.update!(quantity: @item.quantity = @item.quantity - 1)
      else
        Payjp::Charge.create(
          amount: @item.price,
          card: params['payjp-token'],
          currency: 'jpy'
          )
        @item.update!(buyer_id: 2)
        # 仮テスト 0817追記↓↓↓↓↓↓↓↓↓
        @item.update!(quantity: @item.quantity = @item.quantity - 1)
      end
    end
  end

  private

  def prefecture
    # @destinations = Destination.all
    @prefecture = PrefectureFire.find(current_user.destination.prefecture)
  end

  def move_to_root
    redirect_to root_path unless user_signed_in?
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def deliveryfee
    @deliveryfee = DeliveryFee.find(@item.cost)
  end

  def correct_user
    @item = Item.find(params[:id])
    if @item.seller_id == current_user.id
      redirect_to root_path
    end
  end

end

app/views/cards/_main_buy.html.haml
- content_for :css do
  = stylesheet_link_tag 'modules/card_main_buy'

-if @item.quantity == 0
  .buy#short
    .buy__main
      .buy__main__title#soldout
        この商品は売切れました。
      .buy__main__item
        .buy__main__item--photo
          = image_tag @item.images.first.image_url
        .buy__main__item--data
          .name
            = @item.name
          .price
            = @item.price.to_s(:delimited)
            円 (税込)
            = @deliveryfee.value
            
- else
  .buy
    .buy__main
      .buy__main__title
        購入内容確認
      .buy__main__item
        .buy__main__item--photo
          = image_tag @item.images.first.image_url
        .buy__main__item--data
          .name
            = @item.name
          .price
            = @item.price.to_s(:delimited)
            円 (税込)
            = @deliveryfee.value
      .buy__main__claim
        .title
          お支払金額
        .price
          = @item.price.to_s(:delimited)
          円
      .buy__main__card__title
        お支払方法
      - if @card_info.blank?
        .buy__main__newlink
          .icon 
            = icon("far", "plus-square")
          .text
            =link_to "クレジットカードを登録する", new_card_path, data: {"turbolinks" => false}, class:"text"
        .buy__main__buynow
          = form_tag(action: :pay, method: :post) do
            %script.payjp-button{src: "https://checkout.pay.jp", type: "text/javascript" ,"data-text": "クレジット情報を登録しないで購入する" ,"data-key": "pk_test_3f9419193d0e8fa1db45f647","data-lang": "ja"}
        .buy__main__buynow--text
          ※商品の購入はクレジットカード決済のみとなっております。「クレジットカードを登録する」を選ぶと２回目以降の購入がスムーズとなります。１回限りの購入のお客様は「クレジット情報を登録しないで購入する」をクリックし、必要な支払い情報を入力して「カードで支払う」をクリックして下さい。
      - else
        .buy__main__card
          = "**** **** **** " + @card_info.last4
        .buy__main__card
          = @card_info.exp_month.to_s + "月 / " + @card_info.exp_year.to_s.slice(2,3) + "年"
        .buy__main__card
          = image_tag "credit_logo/#{@card_src}", alt: @card_info.brand
      .buy__main__address
        配送先
      .buy__main__address
        
        = "〒#{current_user.destination.postcode}"
      .buy__main__address
        = @prefecture[:name]
        = current_user.destination.city
        = current_user.destination.house_number
        = current_user.destination.building_name
      .buy__main__address
        = current_user.destination.first_name_destination
        = current_user.destination.family_name_destination
      - if @card_info.present?
        .buy__main__btn
          = link_to '購入する', pay_card_path(@item.id), method: :post, class: 'link'

app/views/cards/buy.html.haml
= render partial: "items/header"
= render 'main_buy'
= render partial: "items/banner"
= render partial: "items/footer"

app/views/cards/delete_done.html.haml
= render partial: "items/header"

- content_for :css do
  = stylesheet_link_tag 'modules/_done'

.user
  .done
    .done__title
      クレジット情報を削除しました

= render partial: "items/banner"
= render partial: "items/footer"

app/views/cards/new.html.haml
= render partial: "items/header"

- content_for :css do
  = stylesheet_link_tag 'modules/new_card'

  
.account__page
  .account__page__header
      
  .account__page__main
    = form_tag(cards_path, method: :post, id: 'charge-form') do
      .account__page__main__content
        .field__title
          クレジット情報の登録
        .field__label
          .name
            %label お取扱できるクレジットカード
        .field_label
          = image_tag(image_path('credit_logo/visa.gif'), class: 'credit_logo')
          = image_tag(image_path('credit_logo/mc.png'), class: 'credit_logo')
          = image_tag(image_path('credit_logo/jcb.gif'), class: 'credit_logo')
          = image_tag(image_path('credit_logo/amex.gif'), class: 'credit_logo')
          = image_tag(image_path('credit_logo/diners.gif'), class: 'credit_logo')
          = image_tag(image_path('credit_logo/discover.gif'), class: 'credit_logo')
        .field__label
          .name
            %label カード番号
          .required
            必須
        .field__input
          = text_field_tag "", "", class: "textbox", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        .field__label
          .name
            %label 有効期限
          .required
            必須
        .field_input
          %select#exp_month{type: "text", class: "numberbox"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月/
          %select#exp_year{type: "text", class: "numberbox"}
            %option{value: ""} --
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
            %option{value: "2030"}30
          %span 年
        .field__label
          .name
            %label セキュリティコード
          .required
            必須
        .field__input
          = text_field_tag "", "", class: "textbox", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        #card_token
          = submit_tag "クレジット情報を登録する", id: "token_submit", class: "submit-btn"    
= render partial: "items/banner"
= render partial: "items/footer"

app/views/cards/pay.html.haml
- content_for :css do
  = stylesheet_link_tag 'modules/post_done'



= render partial: "items/header"


.done
  .done__title
    購入手続が完了しました
  .done__backlink
    =link_to root_path, class:"link" do
      トップページへ戻る

= render partial: "items/banner"
= render partial: "items/footer"

app/views/cards/registration_done.html.haml
= render partial: "items/header"

- content_for :css do
  = stylesheet_link_tag 'modules/_done'

.user
  .done
    .done__title
      クレジット情報を登録しました
      
= render partial: "items/banner"
= render partial: "items/footer"

app/views/cards/show.html.haml
= render partial: "items/header"

.user
  .card
    .card__body
      .card__body__title
        クレジット情報の確認/削除
      .card__body__main
        .card__body__main__title
          Your Credit Card
        .card__body__main__data
          = "**** **** **** " + @card_info.last4
        .card__body__main__data
          = @card_info.exp_month.to_s + "月 / " + @card_info.exp_year.to_s.slice(2,3) + "年"
        .card__body__main__brand
          = image_tag "credit_logo/#{@card_src}", alt: @card_info.brand
      .delete_btn
        = link_to card_path, method: :delete, class: "btn" do
          クレジット情報を削除する

= render partial: "items/banner"
= render partial: "items/footer"